In [2]:
import numpy as np
import pandas as pd

In [3]:
df = pd.read_csv('../Data Sets/PandasDataset/MulVarLinReg_SomeNull.csv')
df.head()

    Humi   WindSp  WindBe     Visi     Pres      Temp
0   0.89      NaN   251.0  15.8263  1015.13  9.472222
1    NaN  14.2646   259.0      NaN  1015.63       NaN
2    NaN   3.9284   204.0  14.9569  1015.94       NaN
3   0.83  14.1036     NaN      NaN  1016.41  8.288889
4   0.83  11.0446   259.0  15.8263  1016.51  8.755556

In [4]:
df = pd.read_csv('../Data Sets/PandasDataset/MulVarLinReg_SomeNull.csv', header = None).add_prefix('Weather Parameter ')
df.head()

,Weather Parameter 0,Weather Parameter 1,Weather Parameter 2,Weather Parameter 3,Weather Parameter 4,Weather Parameter 5
0,Humi,WindSp,WindBe,Visi,Pres,Temp
1,0.89,NaN,251,15.8263,1015.13,9.472222222
2,NaN,14.2646,259,NaN,1015.63,NaN
3,NaN,3.9284,204,14.9569,1015.94,NaN
4,0.83,14.1036,NaN,NaN,1016.41,8.288888889

In [5]:
df = pd.read_csv('../Data Sets/PandasDataset/MulVarLinReg_SomeNull.csv', nrows = 2)
df.head()

    Humi   WindSp  WindBe     Visi     Pres      Temp
0   0.89      NaN     251  15.8263  1015.13  9.472222
1    NaN  14.2646     259      NaN  1015.63       NaN

In [6]:
df = pd.read_csv('../Data Sets/PandasDataset/MulVarLinReg_SomeNull.csv', skiprows = 5)
df.head()

   0.83  11.0446    259  15.8263  1016.51  8.755555556
0  0.85  13.9587  258.0  14.9569  1016.66     9.222222
1  0.95  12.3648  259.0   9.9820  1016.72     7.733333
2  0.89  14.1519  260.0   9.9820  1016.84     8.772222
3  0.82  11.3183  259.0   9.9820  1017.37    10.822222
4  0.72  12.5258  279.0   9.9820  1017.22    13.772222

In [7]:
df = pd.read_csv('../Data Sets/PandasDataset/MulVarLinReg_SomeNull.csv', index_col = ['WindBe'])
df.head()

         Humi   WindSp     Visi     Pres      Temp
WindBe
251.0    0.89      NaN  15.8263  1015.13  9.472222
259.0     NaN  14.2646      NaN  1015.63       NaN
204.0     NaN   3.9284  14.9569  1015.94       NaN
NaN      0.83  14.1036      NaN  1016.41  8.288889
259.0    0.83  11.0446  15.8263  1016.51  8.755556

In [8]:
df = pd.read_csv('../Data Sets/PandasDataset/MulVarLinReg_SomeNull.csv', skiprows = 5, names = ['Humi', 'WindSp', 'WindBe', 'Visi', 'Pres', 'Temp'])
df.head()

   Humi   WindSp  WindBe     Visi     Pres       Temp
0  0.83  11.0446   259.0  15.8263  1016.51   8.755556
1  0.85  13.9587   258.0  14.9569  1016.66   9.222222
2  0.95  12.3648   259.0   9.9820  1016.72   7.733333
3  0.89  14.1519   260.0   9.9820  1016.84   8.772222
4  0.82  11.3183   259.0   9.9820  1017.37  10.822222

In [9]:
df = pd.read_csv('../Data Sets/PandasDataset/MulVarLinReg_SomeNull.csv', usecols = ['WindBe', 'Visi', ' Temp'])
df.head()

   WindBe     Visi      Temp
0   251.0  15.8263  9.472222
1   259.0      NaN       NaN
2   204.0  14.9569       NaN
3     NaN      NaN  8.288889
4   259.0  15.8263  8.755556

In [10]:
df = pd.read_csv('../Data Sets/PandasDataset/MulVarLinReg_SomeNull.csv', keep_default_na = False)
df.head()

   Humi   WindSp WindBe     Visi     Pres         Temp
0  0.89     NULL    251  15.8263  1015.13  9.472222222
1  NULL  14.2646    259     NULL  1015.63         NULL
2  NULL   3.9284    204  14.9569  1015.94         NULL
3  0.83  14.1036   NULL     NULL  1016.41  8.288888889
4  0.83  11.0446    259  15.8263  1016.51  8.755555556

In [11]:
df = pd.read_csv('../Data Sets/PandasDataset/MulVarLinReg_NotAnyNull.csv', na_filter = False)
df.head()

    Humi   WindSp  WindBe     Visi     Pres      Temp
0   0.89  14.1197     251  15.8263  1015.13  9.472222
1   0.86  14.2646     259  15.8263  1015.63  9.355556
2   0.89   3.9284     204  14.9569  1015.94  9.377778
3   0.83  14.1036     269  15.8263  1016.41  8.288889
4   0.83  11.0446     259  15.8263  1016.51  8.755556

In [12]:
df = pd.read_csv('../Data Sets/PandasDataset/MulVarLinReg_SomeNull.csv', dtype = {'WindBe' : 'float64'})
df.head()

    Humi   WindSp  WindBe     Visi     Pres      Temp
0   0.89      NaN   251.0  15.8263  1015.13  9.472222
1    NaN  14.2646   259.0      NaN  1015.63       NaN
2    NaN   3.9284   204.0  14.9569  1015.94       NaN
3   0.83  14.1036     NaN      NaN  1016.41  8.288889
4   0.83  11.0446   259.0  15.8263  1016.51  8.755556

In [13]:
df = pd.read_csv('../Data Sets/PandasDataset/MulVarLinReg_SomeNull.csv', na_values = '251.0')
df.head()

    Humi   WindSp  WindBe     Visi     Pres      Temp
0   0.89      NaN     NaN  15.8263  1015.13  9.472222
1    NaN  14.2646   259.0      NaN  1015.63       NaN
2    NaN   3.9284   204.0  14.9569  1015.94       NaN
3   0.83  14.1036     NaN      NaN  1016.41  8.288889
4   0.83  11.0446   259.0  15.8263  1016.51  8.755556

In [14]:
df = pd.read_csv('../Data Sets/PandasDataset/MulVarLinReg_SomeNull.csv')
df.head()

    Humi   WindSp  WindBe     Visi     Pres      Temp
0   0.89      NaN   251.0  15.8263  1015.13  9.472222
1    NaN  14.2646   259.0      NaN  1015.63       NaN
2    NaN   3.9284   204.0  14.9569  1015.94       NaN
3   0.83  14.1036     NaN      NaN  1016.41  8.288889
4   0.83  11.0446   259.0  15.8263  1016.51  8.755556

In [15]:
df.isnull()

        Humi   WindSp  WindBe   Visi   Pres   Temp
0      False     True   False  False  False  False
1       True    False   False   True  False   True
2       True    False   False  False  False   True
3      False    False    True   True  False  False
4      False    False   False  False  False  False
...      ...      ...     ...    ...    ...    ...
96448  False    False   False  False  False  False
96449  False    False   False  False  False  False
96450  False    False   False  False  False  False
96451  False    False   False  False  False  False
96452  False    False   False  False  False  False

[96453 rows x 6 columns]

In [16]:
df.isnull().sum()

 Humi      2
 WindSp    5
WindBe     7
Visi       2
Pres       7
 Temp      5
dtype: int64

In [17]:
df.isnull().sum().sum()

np.int64(28)

In [18]:
df.notnull()

        Humi   WindSp  WindBe   Visi  Pres   Temp
0       True    False    True   True  True   True
1      False     True    True  False  True  False
2      False     True    True   True  True  False
3       True     True   False  False  True   True
4       True     True    True   True  True   True
...      ...      ...     ...    ...   ...    ...
96448   True     True    True   True  True   True
96449   True     True    True   True  True   True
96450   True     True    True   True  True   True
96451   True     True    True   True  True   True
96452   True     True    True   True  True   True

[96453 rows x 6 columns]

In [19]:
df.notnull().sum().sum()

np.int64(578690)

In [20]:
df.dropna(axis = 0)

        Humi   WindSp  WindBe     Visi     Pres       Temp
4       0.83  11.0446   259.0  15.8263  1016.51   8.755556
5       0.85  13.9587   258.0  14.9569  1016.66   9.222222
6       0.95  12.3648   259.0   9.9820  1016.72   7.733333
7       0.89  14.1519   260.0   9.9820  1016.84   8.772222
8       0.82  11.3183   259.0   9.9820  1017.37  10.822222
...      ...      ...     ...      ...      ...        ...
96448   0.43  10.9963    31.0  16.1000  1014.36  26.016667
96449   0.48  10.0947    20.0  15.5526  1015.16  24.583333
96450   0.56   8.9838    30.0  16.1000  1015.66  22.038889
96451   0.60  10.5294    20.0  16.1000  1015.95  21.522222
96452   0.61   5.8765    39.0  15.5204  1016.16  20.438889

[96429 rows x 6 columns]

In [21]:
df.dropna(axis = 1)

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, ...]

[96453 rows x 0 columns]

In [22]:
df.dropna(how = 'all')

        Humi   WindSp  WindBe     Visi     Pres       Temp
0       0.89      NaN   251.0  15.8263  1015.13   9.472222
1        NaN  14.2646   259.0      NaN  1015.63        NaN
2        NaN   3.9284   204.0  14.9569  1015.94        NaN
3       0.83  14.1036     NaN      NaN  1016.41   8.288889
4       0.83  11.0446   259.0  15.8263  1016.51   8.755556
...      ...      ...     ...      ...      ...        ...
96448   0.43  10.9963    31.0  16.1000  1014.36  26.016667
96449   0.48  10.0947    20.0  15.5526  1015.16  24.583333
96450   0.56   8.9838    30.0  16.1000  1015.66  22.038889
96451   0.60  10.5294    20.0  16.1000  1015.95  21.522222
96452   0.61   5.8765    39.0  15.5204  1016.16  20.438889

[96453 rows x 6 columns]

In [23]:
df.dropna(thresh = 4)

        Humi   WindSp  WindBe     Visi     Pres       Temp
0       0.89      NaN   251.0  15.8263  1015.13   9.472222
2        NaN   3.9284   204.0  14.9569  1015.94        NaN
3       0.83  14.1036     NaN      NaN  1016.41   8.288889
4       0.83  11.0446   259.0  15.8263  1016.51   8.755556
5       0.85  13.9587   258.0  14.9569  1016.66   9.222222
...      ...      ...     ...      ...      ...        ...
96448   0.43  10.9963    31.0  16.1000  1014.36  26.016667
96449   0.48  10.0947    20.0  15.5526  1015.16  24.583333
96450   0.56   8.9838    30.0  16.1000  1015.66  22.038889
96451   0.60  10.5294    20.0  16.1000  1015.95  21.522222
96452   0.61   5.8765    39.0  15.5204  1016.16  20.438889

[96452 rows x 6 columns]

In [24]:
df.dropna(subset = [' WindSp', ' Temp'])

        Humi   WindSp  WindBe     Visi     Pres       Temp
3       0.83  14.1036     NaN      NaN  1016.41   8.288889
4       0.83  11.0446   259.0  15.8263  1016.51   8.755556
5       0.85  13.9587   258.0  14.9569  1016.66   9.222222
6       0.95  12.3648   259.0   9.9820  1016.72   7.733333
7       0.89  14.1519   260.0   9.9820  1016.84   8.772222
...      ...      ...     ...      ...      ...        ...
96448   0.43  10.9963    31.0  16.1000  1014.36  26.016667
96449   0.48  10.0947    20.0  15.5526  1015.16  24.583333
96450   0.56   8.9838    30.0  16.1000  1015.66  22.038889
96451   0.60  10.5294    20.0  16.1000  1015.95  21.522222
96452   0.61   5.8765    39.0  15.5204  1016.16  20.438889

[96443 rows x 6 columns]

In [25]:
df.fillna('Filled')

         Humi   WindSp  WindBe     Visi     Pres       Temp
0        0.89   Filled   251.0  15.8263  1015.13   9.472222
1      Filled  14.2646   259.0   Filled  1015.63     Filled
2      Filled   3.9284   204.0  14.9569  1015.94     Filled
3        0.83  14.1036  Filled   Filled  1016.41   8.288889
4        0.83  11.0446   259.0  15.8263  1016.51   8.755556
...       ...      ...     ...      ...      ...        ...
96448    0.43  10.9963    31.0     16.1  1014.36  26.016667
96449    0.48  10.0947    20.0  15.5526  1015.16  24.583333
96450    0.56   8.9838    30.0     16.1  1015.66  22.038889
96451     0.6  10.5294    20.0     16.1  1015.95  21.522222
96452    0.61   5.8765    39.0  15.5204  1016.16  20.438889

[96453 rows x 6 columns]

In [26]:
df.fillna({' Humi' : 'Indeterministic', 'WindBe' : 'Interpolate'})

                  Humi   WindSp       WindBe     Visi     Pres       Temp
0                 0.89      NaN        251.0  15.8263  1015.13   9.472222
1      Indeterministic  14.2646        259.0      NaN  1015.63        NaN
2      Indeterministic   3.9284        204.0  14.9569  1015.94        NaN
3                 0.83  14.1036  Interpolate      NaN  1016.41   8.288889
4                 0.83  11.0446        259.0  15.8263  1016.51   8.755556
...                ...      ...          ...      ...      ...        ...
96448             0.43  10.9963         31.0  16.1000  1014.36  26.016667
96449             0.48  10.0947         20.0  15.5526  1015.16  24.583333
96450             0.56   8.9838         30.0  16.1000  1015.66  22.038889
96451              0.6  10.5294         20.0  16.1000  1015.95  21.522222
96452             0.61   5.8765         39.0  15.5204  1016.16  20.438889

[96453 rows x 6 columns]

In [27]:
df.ffill()

        Humi   WindSp  WindBe     Visi     Pres       Temp
0       0.89      NaN   251.0  15.8263  1015.13   9.472222
1       0.89  14.2646   259.0  15.8263  1015.63   9.472222
2       0.89   3.9284   204.0  14.9569  1015.94   9.472222
3       0.83  14.1036   204.0  14.9569  1016.41   8.288889
4       0.83  11.0446   259.0  15.8263  1016.51   8.755556
...      ...      ...     ...      ...      ...        ...
96448   0.43  10.9963    31.0  16.1000  1014.36  26.016667
96449   0.48  10.0947    20.0  15.5526  1015.16  24.583333
96450   0.56   8.9838    30.0  16.1000  1015.66  22.038889
96451   0.60  10.5294    20.0  16.1000  1015.95  21.522222
96452   0.61   5.8765    39.0  15.5204  1016.16  20.438889

[96453 rows x 6 columns]

In [28]:
df.bfill(axis = 1)

          Humi    WindSp   WindBe       Visi     Pres       Temp
0       0.8900  251.0000   251.00    15.8263  1015.13   9.472222
1      14.2646   14.2646   259.00  1015.6300  1015.63        NaN
2       3.9284    3.9284   204.00    14.9569  1015.94        NaN
3       0.8300   14.1036  1016.41  1016.4100  1016.41   8.288889
4       0.8300   11.0446   259.00    15.8263  1016.51   8.755556
...        ...       ...      ...        ...      ...        ...
96448   0.4300   10.9963    31.00    16.1000  1014.36  26.016667
96449   0.4800   10.0947    20.00    15.5526  1015.16  24.583333
96450   0.5600    8.9838    30.00    16.1000  1015.66  22.038889
96451   0.6000   10.5294    20.00    16.1000  1015.95  21.522222
96452   0.6100    5.8765    39.00    15.5204  1016.16  20.438889

[96453 rows x 6 columns]

In [29]:
df = pd.read_csv('../Data Sets/PandasDataset/MulVarLinReg_SomeNull.csv')
df.head()

    Humi   WindSp  WindBe     Visi     Pres      Temp
0   0.89      NaN   251.0  15.8263  1015.13  9.472222
1    NaN  14.2646   259.0      NaN  1015.63       NaN
2    NaN   3.9284   204.0  14.9569  1015.94       NaN
3   0.83  14.1036     NaN      NaN  1016.41  8.288889
4   0.83  11.0446   259.0  15.8263  1016.51  8.755556

In [30]:
df.replace(to_replace = 0.83, value = 'Unknown')

          Humi   WindSp  WindBe     Visi     Pres       Temp
0         0.89      NaN   251.0  15.8263  1015.13   9.472222
1          NaN  14.2646   259.0      NaN  1015.63        NaN
2          NaN   3.9284   204.0  14.9569  1015.94        NaN
3      Unknown  14.1036     NaN      NaN  1016.41   8.288889
4      Unknown  11.0446   259.0  15.8263  1016.51   8.755556
...        ...      ...     ...      ...      ...        ...
96448     0.43  10.9963    31.0  16.1000  1014.36  26.016667
96449     0.48  10.0947    20.0  15.5526  1015.16  24.583333
96450     0.56   8.9838    30.0  16.1000  1015.66  22.038889
96451      0.6  10.5294    20.0  16.1000  1015.95  21.522222
96452     0.61   5.8765    39.0  15.5204  1016.16  20.438889

[96453 rows x 6 columns]

In [31]:
df.replace({' Humi' : 0.83, 'WindBe' : 259.0}, 0)

        Humi   WindSp  WindBe     Visi     Pres       Temp
0       0.89      NaN   251.0  15.8263  1015.13   9.472222
1        NaN  14.2646     0.0      NaN  1015.63        NaN
2        NaN   3.9284   204.0  14.9569  1015.94        NaN
3       0.00  14.1036     NaN      NaN  1016.41   8.288889
4       0.00  11.0446     0.0  15.8263  1016.51   8.755556
...      ...      ...     ...      ...      ...        ...
96448   0.43  10.9963    31.0  16.1000  1014.36  26.016667
96449   0.48  10.0947    20.0  15.5526  1015.16  24.583333
96450   0.56   8.9838    30.0  16.1000  1015.66  22.038889
96451   0.60  10.5294    20.0  16.1000  1015.95  21.522222
96452   0.61   5.8765    39.0  15.5204  1016.16  20.438889

[96453 rows x 6 columns]

In [32]:
df.replace('[0-9]', 0, regex = True)

        Humi   WindSp  WindBe     Visi     Pres       Temp
0       0.89      NaN   251.0  15.8263  1015.13   9.472222
1        NaN  14.2646   259.0      NaN  1015.63        NaN
2        NaN   3.9284   204.0  14.9569  1015.94        NaN
3       0.83  14.1036     NaN      NaN  1016.41   8.288889
4       0.83  11.0446   259.0  15.8263  1016.51   8.755556
...      ...      ...     ...      ...      ...        ...
96448   0.43  10.9963    31.0  16.1000  1014.36  26.016667
96449   0.48  10.0947    20.0  15.5526  1015.16  24.583333
96450   0.56   8.9838    30.0  16.1000  1015.66  22.038889
96451   0.60  10.5294    20.0  16.1000  1015.95  21.522222
96452   0.61   5.8765    39.0  15.5204  1016.16  20.438889

[96453 rows x 6 columns]